ota_password: "tx1Bfa9t+EOaR7BzBKGIVg"
api_password: "tx1Bfa9t+EOaR7BzBKGIVg"

# please regenerate 
# see here https://esphome.io/components/api.html#configuration-variables
api_encryption: "9gyAFGUYoRoe9eehTs7S+ApTnWoL4CdD5TlgSKfn7vI="





