ota_password: "please-set-a-password"
api_password: "please-set-a-password"

# please regenerate 
# see here https://esphome.io/components/api.html#configuration-variables
api_encryption: "oxfBrmLwYLNrBEm58dwzzWlIr8EPQ7fzv5o3R5BPZNQ="
