# Required for devices with Wifi enabled
wifi_ssid: "add_wifi_ssid"
wifi_password: "add-wifi-password-here"
wifi_ap_password: "add-ap-mode-password-here"

# Required for devices with eth enabled
eth_static_ip: "192.168.1.10"
eth_gateway: "192.168.1.1"
eth_subnet: "255.255.255.0"