# Required for devices with Wifi enabled
#wifi_ssid: "petticoats"
#wifi_password: "DragonBalm42"
wifi_ap_password: "xhuh32a8A0Nn"

wifi_ssid: "NETGEAR76"
wifi_password: "magicalowl123"

# Required for devices with eth enabled
#eth_static_ip: "10.100.0.200"
#eth_gateway: "10.100.0.1"
#eth_subnet: "255.255.255.0"