# These substitutions allow the end user to override certain values
substitutions:
  device_name: "6-channel-pwm-controller"
  log_level: "DEBUG"

packages:
  core: !include config/core.yaml
  network_access: !include "config/network/wifi.yaml"
  #network_access: !include config/network/LAN8720.yaml

  # Configure lights
  cwww_light_a: !include 
    file: config/lights/cwww_light.yaml
    vars: 
      light_name: a
      channel_a_assignment: "1.0"
      channel_b_assignment: "1.0"
      channel_c_assignment: "0.5"
      channel_d_assignment: "0.5"
      channel_e_assignment: "0.0"
      channel_f_assignment: "0.0"

  cwww_light_b: !include 
    file: config/lights/cwww_light.yaml
    vars: 
      light_name: b
      channel_a_assignment: "0.0"
      channel_b_assignment: "0.0"
      channel_c_assignment: "0.5"
      channel_d_assignment: "0.5"
      channel_e_assignment: "1.0"
      channel_f_assignment: "1.0"

  # Configure input buttons
  momentary_button_a: !include 
    file: config/input/momentary_button.yaml
    vars: 
      switch_name: a
      switch_gpio: GPIO34

  momentary_button_b: !include 
    file: config/input/momentary_button.yaml
    vars: 
      switch_name: b
      switch_gpio: GPIO35
 
  # Configure Output devices 
  output_channel_a: !include 
    file: config/output/pwm_channel.yaml
    vars: 
      output_name: a
      ledc_gpio: GPIO32
      ledc_min_power: 0.0025

  output_channel_b: !include 
    file: config/output/pwm_channel.yaml
    vars: 
      output_name: b
      ledc_gpio: GPIO33
      ledc_min_power: 0.0025

  output_channel_c: !include 
    file: config/output/pwm_channel.yaml
    vars: 
      output_name: c
      ledc_gpio: GPIO14
      ledc_min_power: 0.0025

  output_channel_d: !include 
    file: config/output/pwm_channel.yaml
    vars: 
      output_name: d
      ledc_gpio: GPIO13
      ledc_min_power: 0.0025

  output_channel_e: !include 
    file: config/output/pwm_channel.yaml
    vars: 
      output_name: e
      ledc_gpio: GPIO16
      ledc_min_power: 0.0025

  output_channel_f: !include 
    file: config/output/pwm_channel.yaml
    vars: 
      output_name: f
      ledc_gpio: GPIO04
      ledc_min_power: 0.0025



